# Generated by Django 5.1.14 on 2025-11-19 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.EmailField(max_length=254, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipovehiculo_vehiculo', models.CharField(choices=[('PRIVADO', 'PRIVADO'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION')], max_length=50)),
                ('tipocombustible_vehiculo', models.CharField(choices=[('EXTRA', 'EXTRA'), ('DIESEL', 'DIESEL'), ('SUPER', 'SUPER')], max_length=50)),
                ('matricula_vehiculo', models.CharField(max_length=100, unique=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='proyectos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionVehiculo',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UbicacionVehiculos', to='proyectos.vehiculo')),
            ],
        ),
    ]
