# Generated by Django 5.1.14 on 2025-11-24 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugarguardado',
            fields=[
                ('id_Lugarguardado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Lugarguardado', models.CharField(max_length=100)),
                ('latitud_Lugarguardado', models.FloatField()),
                ('longitud_Lugarguardado', models.FloatField()),
                ('fecha_guardado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lugarguardados', to='proyectos.usuario')),
            ],
        ),
    ]
