# Generated by Django 5.1.14 on 2025-11-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_lugarguardado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarguardado',
            name='nombre_Lugarguardado',
            field=models.CharField(max_length=900),
        ),
    ]
