# Generated by Django 5.1.14 on 2025-12-14 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_lugarguardado_nombre_lugarguardado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoMapa',
            fields=[
                ('id_nodo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tipo', models.CharField(choices=[('INTERSECCION', 'Intersección'), ('PUNTO_INTERES', 'Punto de interés'), ('PARROQUIA', 'Parroquia')], default='INTERSECCION', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioCombustible',
            fields=[
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('EXTRA', 'EXTRA'), ('DIESEL', 'DIESEL'), ('SUPER', 'SUPER'), ('ECOPAIS', 'ECOPAIS')], max_length=20)),
                ('precio_por_litro', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TramoVial',
            fields=[
                ('id_tramo', models.AutoField(primary_key=True, serialize=False)),
                ('distancia_km', models.FloatField()),
                ('tiempo_base_min', models.FloatField()),
                ('tipo_via', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural'), ('PRINCIPAL', 'Principal'), ('SECUNDARIA', 'Secundaria')], max_length=50)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_llegada', to='proyectos.nodomapa')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_salida', to='proyectos.nodomapa')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.lugarguardado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.ubicacionvehiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='proyectos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='proyectos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RutaOpcion',
            fields=[
                ('id_ruta_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('OPTIMA', 'Óptima'), ('LARGA', 'Larga'), ('SEGURA', 'Segura')], max_length=10)),
                ('tiempo_min', models.FloatField()),
                ('distancia_km', models.FloatField()),
                ('consumo_litros', models.FloatField(blank=True, null=True)),
                ('costo_estimado', models.FloatField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='proyectos.viaje')),
            ],
        ),
    ]
