# Generated by Django 5.1.14 on 2025-12-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_nodomapa_preciocombustible_tramovial_viaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiporol',
            field=models.CharField(choices=[('USUARIO', 'USUARIO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], default='USUARIO', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono_institucional', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyectos.usuario')),
            ],
        ),
    ]
