# Generated by Django 5.1.14 on 2025-12-25 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_usuario_tiporol_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEvento',
            fields=[
                ('id_usuario_evento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_evento', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO'), ('ATRASADO', 'ATRASADO'), ('NO COMPLETADO', 'NO COMPLETADO')], default='PENDIENTE', max_length=20)),
                ('estado_fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistVehiculo',
            fields=[
                ('id_checklist', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('licencia_conducir', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('tarjeta_circulacion', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('poliza_impresa', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('poliza_digital', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('verificacion_vehicular', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('factura_propiedad', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('llantas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('frenos', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('luces', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('fluidos_aceite', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('fluido_agua', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('bateria_general', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cinturones', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('limpiaparabrisas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_aceite', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_refrigerante', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_temperatura', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_bateria', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_filtro_aire', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_fugas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('motor_combustible', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('amortiguadores', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('alineacion', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('soportes_motor', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('caja', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('embrague', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('triangulo', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('chaleco', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('extintor', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('gato_llave', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('botiquin', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('linterna', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('cables_corriente', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('tacos_ruedas', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('llanta_reparacion', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_item', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAdmin',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('inicio_fecha', models.DateField()),
                ('inicio_hora', models.TimeField()),
                ('fin_fecha', models.DateField(blank=True, null=True)),
                ('fin_hora', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pedido', models.TextField(blank=True, null=True)),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('ENTREGADO', 'ENTREGADO'), ('CANCELADO', 'CANCELADO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_proveedor', models.EmailField(max_length=254, unique=True)),
                ('ruc_proveedor', models.CharField(max_length=13, unique=True)),
                ('estado_proveedor', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RendimientoVehiculoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRIVADO', 'PRIVADO'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION')], max_length=20)),
                ('km_l_ciudad', models.FloatField()),
                ('km_l_carretera', models.FloatField()),
                ('idle_l_h', models.FloatField(default=0.8)),
            ],
        ),
        migrations.AddField(
            model_name='rutaopcion',
            name='combustible_tipo',
            field=models.CharField(blank=True, choices=[('EXTRA', 'EXTRA'), ('DIESEL', 'DIESEL'), ('SUPER', 'SUPER'), ('ECOPAIS', 'ECOPAIS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rutaopcion',
            name='tipo',
            field=models.CharField(choices=[('OPTIMA', 'OPTIMA'), ('LARGA', 'LARGA'), ('SEGURA', 'SEGURA')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rutaopcion',
            constraint=models.UniqueConstraint(fields=('viaje', 'tipo'), name='uniq_viaje_tipo'),
        ),
        migrations.AddField(
            model_name='asignacionevento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.usuario'),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='proyectos.usuario'),
        ),
        migrations.AddField(
            model_name='eventoadmin',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.administrador'),
        ),
        migrations.AddField(
            model_name='asignacionevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.eventoadmin'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.eventoadmin'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionevento',
            unique_together={('usuario', 'evento')},
        ),
    ]
