# Generated by Django 5.1.14 on 2025-12-30 03:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_asignacionevento_checklistvehiculo_detallepedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('numero_factura', models.CharField(help_text='Ej: 001-001-000000123', max_length=30, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado_factura', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ANULADA', 'ANULADA')], default='PENDIENTE', max_length=50)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, help_text='N° transferencia, depósito, etc.', max_length=100, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('RECHAZADO', 'RECHAZADO')], default='CONFIRMADO', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='proyectos.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Salvoconducto',
            fields=[
                ('id_salvoconducto', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('VENCIDO', 'VENCIDO'), ('ANULADO', 'ANULADO')], default='VIGENTE', max_length=20)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='salvoconductos_qr/')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='salvoconductos_pdf/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.vehiculo')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyectos.viaje')),
            ],
        ),
    ]
