# Generated by Django 5.1.14 on 2026-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_factura_pago_salvoconducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
