# Generated by Django 5.1.14 on 2026-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_usuario_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
