# Generated by Django 5.1.14 on 2026-01-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_factura_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevento',
            name='motivo_atrasado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionevento',
            name='motivo_no_completado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
