# Generated by Django 5.1.14 on 2026-01-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_asignacionevento_motivo_atrasado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='cilindraje',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion_auto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_placa',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipovehiculo_vehiculo',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION'), ('CAMIONETA', 'CAMIONETA')], max_length=50),
        ),
    ]
