# Generated by Django 5.1.14 on 2026-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_vehiculo_cilindraje_vehiculo_descripcion_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipocombustible_vehiculo',
            field=models.CharField(choices=[('EXTRA', 'EXTRA'), ('DIESEL', 'DIESEL'), ('SUPER', 'SUPER'), ('ECOPAIS', 'ECOPAIS')], max_length=50),
        ),
    ]
