# Generated by Django 5.1.14 on 2026-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_alter_vehiculo_tipocombustible_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimientovehiculotipo',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION')], max_length=20),
        ),
    ]
