# Generated by Django 5.1.14 on 2026-01-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_alter_rendimientovehiculotipo_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendimientoVehiculoTipo',
        ),
    ]
