# Generated by Django 5.1.14 on 2026-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_delete_rendimientovehiculotipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendimientoVehiculoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION')], max_length=20)),
                ('km_l_ciudad', models.FloatField()),
                ('km_l_carretera', models.FloatField()),
                ('idle_l_h', models.FloatField(default=0.8)),
            ],
        ),
    ]
