# Generated by Django 5.1.14 on 2026-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_rendimientovehiculotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimientovehiculotipo',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION'), ('CAMIONETA', 'CAMIONETA')], max_length=20),
        ),
    ]
