# Generated by Django 5.1.14 on 2026-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_alter_rendimientovehiculotipo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendimientovehiculotipo',
            name='idle_l_h',
        ),
        migrations.RemoveField(
            model_name='rendimientovehiculotipo',
            name='km_l_carretera',
        ),
        migrations.RemoveField(
            model_name='rendimientovehiculotipo',
            name='km_l_ciudad',
        ),
        migrations.AddField(
            model_name='rendimientovehiculotipo',
            name='km_l_promedio',
            field=models.FloatField(default=10.0, help_text='Rendimiento promedio en km/L'),
            preserve_default=False,
        ),
    ]
