# Generated by Django 5.1.14 on 2026-01-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_remove_rendimientovehiculotipo_idle_l_h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_placa',
        ),
    ]
