# Generated by Django 5.1.14 on 2026-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_remove_vehiculo_numero_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimientovehiculotipo',
            name='tipo',
            field=models.CharField(choices=[('AUTOMOVIL', 'AUTOMOVIL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION'), ('CAMIONETA', 'CAMIONETA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipovehiculo_vehiculo',
            field=models.CharField(choices=[('AUTOMOVIL', 'AUTOMOVIL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMION'), ('CAMIONETA', 'CAMIONETA')], max_length=50),
        ),
    ]
