# Generated by Django 5.1.14 on 2026-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_alter_rendimientovehiculotipo_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='descripcion_auto',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
