# Generated by Django 5.1.14 on 2026-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_remove_vehiculo_descripcion_auto_vehiculo_peso_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
