# Generated by Django 5.1.14 on 2026-01-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_vehiculo_nombre_producto_vehiculo_peso_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='peso_adicional',
        ),
        migrations.CreateModel(
            name='CargaVehiculo',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('peso_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='proyectos.vehiculo')),
            ],
        ),
    ]
