# Generated by Django 5.1.14 on 2026-02-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindraje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
