# Generated by Django 5.1.14 on 2026-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0025_alter_vehiculo_cilindraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaopcion',
            name='tipo',
            field=models.CharField(choices=[('OPTIMA', 'OPTIMA'), ('ALTERNATIVA', 'ALTERNATIVA')], max_length=20),
        ),
    ]
