# Generated by Django 6.0.6 on 2026-07-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_alter_rutaopcion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovial',
            name='geometria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
