# Generated by Django 6.0.6 on 2026-07-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0027_tramovial_geometria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipocombustible_vehiculo',
            field=models.CharField(choices=[('EXTRA', 'EXTRA'), ('DIESEL', 'DIÉSEL'), ('SUPER', 'SÚPER'), ('ECOPAIS', 'ECOPAÍS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipovehiculo_vehiculo',
            field=models.CharField(choices=[('AUTOMOVIL', 'AUTOMÓVIL'), ('TAXI', 'TAXI'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMION', 'CAMIÓN'), ('CAMIONETA', 'CAMIONETA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='proyectos.usuario'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('usuario',), name='un_vehiculo_por_usuario'),
        ),
    ]
