# Generated by Django 6.0.6 on 2026-07-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_alter_vehiculo_tipocombustible_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCarga',
            fields=[
                ('id_producto_carga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('marca_producto', models.CharField(blank=True, max_length=100)),
                ('presentacion_producto', models.CharField(choices=[('GALON', 'GALÓN'), ('JABA', 'JABA'), ('PAQUETE', 'PAQUETE'), ('BOTELLA', 'BOTELLA'), ('CAJA', 'CAJA'), ('FUNDA', 'FUNDA'), ('UNIDAD', 'UNIDAD')], max_length=20)),
                ('descripcion_producto', models.CharField(blank=True, max_length=250)),
                ('peso_unitario_kg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre_producto', 'marca_producto', 'presentacion_producto'],
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='PlanCarga',
            fields=[
                ('id_plan_carga', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_planificada', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('LISTO', 'LISTO'), ('CANCELADO', 'CANCELADO')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_carga_creados', to='proyectos.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_carga', to='proyectos.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_planificada', 'vehiculo__matricula_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanCarga',
            fields=[
                ('id_detalle_plan_carga', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('peso_unitario_kg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('peso_subtotal_kg', models.DecimalField(decimal_places=2, max_digits=11)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyectos.plancarga')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_plan', to='proyectos.productocarga')),
            ],
            options={
                'ordering': ['producto__nombre_producto'],
            },
        ),
        migrations.AddConstraint(
            model_name='plancarga',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'fecha_planificada'), name='un_plan_carga_por_vehiculo_fecha'),
        ),
        migrations.AddConstraint(
            model_name='detalleplancarga',
            constraint=models.UniqueConstraint(fields=('plan', 'producto'), name='producto_unico_por_plan_carga'),
        ),
    ]
