"""
Django settings for proyectos project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
IS_RENDER = os.environ.get("RENDER", "").lower() == "true"

# En Render se debe definir SECRET_KEY como variable de entorno.
# El valor por defecto existe únicamente para desarrollo local.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-only-change-me",
)

# Nunca activar DEBUG en Render.
DEBUG = not IS_RENDER

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL", "").rstrip("/")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Permite añadir dominio(s) personalizados separados por coma sin tocar el código.
for host in os.environ.get("EXTRA_ALLOWED_HOSTS", "").split(","):
    host = host.strip()
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_URL:
    CSRF_TRUSTED_ORIGINS.append(RENDER_EXTERNAL_URL)
elif RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Permite añadir orígenes adicionales separados por coma, por ejemplo un dominio propio.
for origin in os.environ.get("EXTRA_CSRF_TRUSTED_ORIGINS", "").split(","):
    origin = origin.strip().rstrip("/")
    if origin and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Render termina HTTPS en su proxy. Esto hace que Django reconozca correctamente
# las peticiones seguras y evita problemas con cookies/CSRF detrás del proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = IS_RENDER
CSRF_COOKIE_SECURE = IS_RENDER
SECURE_SSL_REDIRECT = IS_RENDER
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

# URL pública usada para QR y cabeceras de servicios externos. En Render se obtiene
# automáticamente; también puede sobrescribirse con PUBLIC_BASE_URL.
PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", RENDER_EXTERNAL_URL).rstrip("/")




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'channels', #activar el chanel django
    'Aplicaciones.proyectos.apps.ProyectosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'proyectos.wsgi.application'# Peticiones normales HTTP
# Configuración para WebSockets con Channels  
ASGI_APPLICATION = 'proyectos.asgi.application' #Django Channels usará ASGI_APPLICATION para los WebSockets.  WebSockets (tiempo real)



# Configuración del backend de canales (Redis)
#CHANNEL_LAYERS = {
#   'default': {
#       'BACKEND': 'channels_redis.core.RedisChannelLayer',
#       'CONFIG': {
#           'hosts': [(
#              os.environ.get('REDIS_URL', 'redis://red-d7l5nttckfvc73fbgfi0:6379')
#
#           )],
#      },
# },
#}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Render: usar la Internal Database URL en DATABASE_URL.
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desarrollo local: conserva la base PostgreSQL que ya utilizaba el proyecto.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "mapas"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "root"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }





# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'proyectos/static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



#CONFIGURANDO CARPETA PARA SUBIR ARCHIVOS
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}




CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "").strip()
GOOGLE_MAPS_SERVER_API_KEY = os.environ.get("GOOGLE_MAPS_SERVER_API_KEY", "").strip()



# Clave de superusuario para acciones administrativas sensibles:
# continuar sin validación GPS y crear nuevas cuentas ADMINISTRADOR.
# En producción se configura como RUTAS_MODO_PRUEBA_CLAVE en Render;
# nunca se guarda la contraseña real en GitHub.
RUTAS_MODO_PRUEBA_CLAVE = os.environ.get(
    "RUTAS_MODO_PRUEBA_CLAVE",
    "",
).strip()

# Consulta opcional de cédula para autocompletar nombres/apellidos.
# Puede apuntar a un proveedor autorizado usando una URL con {cedula}
# o a un endpoint que acepte ?cedula=XXXXXXXXXX.
CEDULA_LOOKUP_URL = os.environ.get('CEDULA_LOOKUP_URL', '')
CEDULA_LOOKUP_TOKEN = os.environ.get('CEDULA_LOOKUP_TOKEN', '')

# Identificación simple para solicitudes a Nominatim/OpenStreetMap.
NOMINATIM_USER_AGENT = os.environ.get('NOMINATIM_USER_AGENT', 'DistricC-Tesis/1.0')

# Datos de la persona indicada en la documentación para la sección final
# de solicitud/constancia de validación de los informes PDF.
PDF_VALIDADOR_NOMBRES = os.environ.get('PDF_VALIDADOR_NOMBRES', '')
PDF_VALIDADOR_APELLIDOS = os.environ.get('PDF_VALIDADOR_APELLIDOS', '')
PDF_VALIDADOR_DOCUMENTO = os.environ.get('PDF_VALIDADOR_DOCUMENTO', '')
PDF_VALIDADOR_CARGO = os.environ.get('PDF_VALIDADOR_CARGO', 'Responsable de validación')
